---

- name: Ensure Redis is installed from Fedora repository
  dnf:
    state: present
    name: redis
    install_weak_deps: false
  retries: 10
  delay: 1

- name: Ensure redis is configured to use unix socket only
  lineinfile:
    path: /etc/redis.conf
    regexp: '^{{ item.option }}\s'
    line: '{{ item.option }} {{ item.value }}'
  with_items:
    - option: unixsocket
      value: /var/run/redis/redis.sock
    - option: unixsocketperm
      value: 770
    - option: port
      value: 0

- name: Ensure Redis is started and enabled at boot
  service:
    name: redis
    state: started
    enabled: true

- name: Ensure temporary directory is present
  tempfile:
    state: directory
    prefix: redis
  register: tmp_dir
  tags: molecule-idempotence-notest

- name: Ensure httpd access SELinux module is present
  copy:
    src: httpd_redis.te
    dest: "{{ tmp_dir.path }}/httpd_redis.te"
  tags: molecule-idempotence-notest

- name: Ensure httpd access SELinux module is activated
  command: "{{ item }}"
  with_items:
    - checkmodule -M -m -o httpd_redis.mod httpd_redis.te
    - semodule_package -o httpd_redis.pp -m httpd_redis.mod
    - semodule -i httpd_redis.pp
  args:
    chdir: "{{ tmp_dir.path }}"
  changed_when: false
  tags:
    - molecule-notest
    - molecule-idempotence-notest

- name: Ensure temporary directory is absent
  file:
    path: "{{ tmp_dir.path }}"
    state: absent
  when: tmp_dir.path is defined
  tags: molecule-idempotence-notest

- name: Ensure user is member of Redis group
  user:
    name: "{{ redis_user }}"
    groups: redis
    append: true
  when: redis_user is defined
