---
- name: install certain python modules for docker
  hosts: appservers
  become: yes
  tasks:
  - name: install docker
    pip:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
      state: absent
    with_items:
    - { name: docker, version: 2.0.0 }
    - { name: docker-py, version: 1.10.6 }
    - { name: docker-pycreds, version: 0.4.0}
    - { name: six, version: 1.10.0}
