---
common_dnf_automatic_restart: true
common_dnf_install_weak_deps: false
common_dnf_keepcache: false
common_fail2ban_action: "%(action_mwl)s"
common_grub_auto_hide: false
common_grub_hidden_timeout: 0
common_grub_timeout: 1
common_mail_smtp_inet_interfaces: "127.0.0.1"
common_mail_smtp_port: 465
common_mail_smtp_tls: TLS
common_os_hardening: true
common_ssh_hardening: true

# Change "dev-sec.os-hardening" role defaults
ufw_manage_defaults: false
os_auth_pam_passwdqc_enable: false
os_auth_pw_max_age: 99999
os_auth_pw_min_age: 0


# Internal values
_smtp_server: "[{{ common_mail_smtp_host }}]:{{ common_mail_smtp_port }}"
