---

- name: Ensure RpmFusion-free repository is installed
  include_role:
    name: jgoutin.home.rpmfusion
  vars:
    rpmfusion_free: true

- name: Ensure MPD is installed
  dnf:
    state: present
    name:
      - mpd
      - mpc
      - alsa-utils
  retries: 10
  delay: 1

- name: Ensure MPD is configured
  template:
    src: mpd.conf.j2
    dest: /etc/mpd.conf
    owner: root
    group: mpd
    mode: 0740

- name: Ensure MPD service directory is present
  file:
    path: /etc/systemd/system/mpd.service.d/
    state: directory

- name: Ensure Alsa unmute is enabled in MPD service
  template:
    src: alsa-unmute.conf.j2
    dest: "/etc/systemd/system/mpd.service.d/alsa-unmute.conf"

- name: Ensure SElinux booleans are configured for MPD
  seboolean:
    name: "{{ item.name }}"
    state: true
    persistent: true
  when: item.when | default(true)
  with_items:
    - name: mpd_enable_homedirs
    - name: mpd_use_cifs
      when: "{{ mpd_use_cifs | bool }}"
    - name: mpd_use_nfs
      when: "{{ mpd_use_nfs | bool }}"
  tags: molecule-notest  # SELinux is disabled on molecule containers

- name: Ensure temporary directory is present
  tempfile:
    state: directory
    prefix: redis
  register: tmp_dir
  tags: molecule-idempotence-notest

- name: Ensure MPD SELinux module is present
  copy:
    src: mpd_selinux.te
    dest: "{{ tmp_dir.path }}/mpd_selinux.te"
  tags: molecule-idempotence-notest

- name: Ensure MPD SELinux module is activated
  command: "{{ item }}"
  with_items:
    - checkmodule -M -m -o mpd_selinux.mod mpd_selinux.te
    - semodule_package -o mpd_selinux.pp -m mpd_selinux.mod
    - semodule -i mpd_selinux.pp
  args:
    chdir: "{{ tmp_dir.path }}"
  changed_when: false
  tags:
    - molecule-notest
    - molecule-idempotence-notest

- name: Ensure temporary directory is absent
  file:
    path: "{{ tmp_dir.path }}"
    state: absent
  when: tmp_dir.path is defined
  tags: molecule-idempotence-notest

- name: Ensure MPD firewalld zone is present
  firewalld:
    zone: "{{ mpd_firewalld_zone }}"
    state: present
    permanent: true
  when: mpd_firewalld_source is defined

- name: Ensure firewalld is reloaded
  command: firewall-cmd --reload
  changed_when: false
  when: mpd_firewalld_source is defined

- name: Ensure source is defined in firewalld zone
  firewalld:
    zone: "{{ mpd_firewalld_zone }}"
    source: "{{ mpd_firewalld_source }}"
    state: enabled
    permanent: true
    immediate: true
  when: mpd_firewalld_source is defined

- name: Ensure firewalld allow MPD
  firewalld:
    zone: "{{ mpd_firewalld_zone }}"
    service: mpd
    state: enabled
    permanent: true
    immediate: true

- name: Ensure admin firewalld zone allow MPD
  firewalld:
    zone: admin
    service: mpd
    state: enabled
    permanent: true
    immediate: true
  when: common_trusted_firewalld_source is defined

- name: Ensure firewalld allow Zeroconf mDNS
  firewalld:
    zone: "{{ mpd_firewalld_zone }}"
    service: mdns
    state: enabled
    permanent: true
    immediate: true
  when: mpd_zeroconf

- name: Ensure MPD socket service is started
  systemd:
    name: mpd.socket
    state: started
    enabled: true

- name: Ensure the MPD database is up to date
  command: mpc update
  when: mpd_update | bool
  changed_when: false
